import type { Article } from "./types";

// 12 篇文章，涵盖编程(5)、工具(3)、文学(4)类别，publishedAt 分布在最近 2 年内
export const articles: Article[] = [
  {
    id: "1",
    title: "TypeScript 类型体操：从入门到精通",
    excerpt:
      "系统梳理 TypeScript 高级类型用法，包括条件类型、映射类型、模板字面量类型等，结合实战案例深入理解类型系统的强大之处。",
    coverImage: "https://picsum.photos/seed/typescript-advanced/600/400",
    category: "编程",
    publishedAt: new Date("2025-11-20"),
    views: 4820,
    likes: 312,
    comments: 67,
    href: "/articles/typescript-advanced-types",
  },
  {
    id: "2",
    title: "Next.js 15 App Router 完全指南",
    excerpt:
      "全面解析 Next.js App Router 的核心概念：Server Components、Streaming、并行路由和拦截路由，以及如何在真实项目中合理选择渲染模式。",
    coverImage: "https://picsum.photos/seed/nextjs-app-router/600/400",
    category: "编程",
    publishedAt: new Date("2025-09-05"),
    views: 3960,
    likes: 278,
    comments: 54,
    href: "/articles/nextjs-app-router-guide",
  },
  {
    id: "3",
    title: "用 Obsidian 搭建个人知识库的实践",
    excerpt:
      "历时半年的知识管理实践总结。从混乱的收藏夹到结构化的知识库，分享我的目录设计、双链笔记方法论和每日工作流。",
    coverImage: "https://picsum.photos/seed/obsidian-notes/600/400",
    category: "工具",
    publishedAt: new Date("2025-08-12"),
    views: 2340,
    likes: 189,
    comments: 41,
    href: "/articles/obsidian-knowledge-base",
  },
  {
    id: "4",
    title: "《挪威的森林》：青春的哀愁与告别",
    excerpt:
      "村上春树用克制而细腻的笔触描绘了一段无法愈合的青春伤痛。在直子、绿子和渡边之间，我看见了每个人心底那个无处安放的自己。",
    coverImage: "https://picsum.photos/seed/norwegian-wood/600/400",
    category: "文学",
    publishedAt: new Date("2025-07-28"),
    views: 1870,
    likes: 143,
    comments: 38,
    href: "/articles/norwegian-wood",
  },
  {
    id: "5",
    title: "CSS 现代布局：Grid 与 Flexbox 协作指南",
    excerpt:
      "深入对比 Grid 和 Flexbox 的适用场景，通过 10 个典型布局案例，掌握两者协同使用的最佳实践，告别无脑 flex everything。",
    coverImage: "https://picsum.photos/seed/css-grid-flex/600/400",
    category: "编程",
    publishedAt: new Date("2025-06-14"),
    views: 3210,
    likes: 234,
    comments: 49,
    href: "/articles/css-grid-flexbox",
  },
  {
    id: "6",
    title: "我的命令行工具箱：2025 年更新版",
    excerpt:
      "整理了我日常开发中最依赖的 20 个命令行工具，包括 zoxide、bat、ripgrep、lazygit 等，每款都附有配置片段和实用技巧。",
    coverImage: "https://picsum.photos/seed/cli-tools-2025/600/400",
    category: "工具",
    publishedAt: new Date("2025-05-03"),
    views: 2780,
    likes: 201,
    comments: 36,
    href: "/articles/cli-tools-2025",
  },
  {
    id: "7",
    title: "《活着》：在苦难中寻找存在的重量",
    excerpt:
      "余华的文字像刀，割开命运的褶皱，露出底层人民最真实的痛苦与韧性。读完之后久久无法平静，忍不住想写下这些文字。",
    coverImage: "https://picsum.photos/seed/alive-book/600/400",
    category: "文学",
    publishedAt: new Date("2025-03-22"),
    views: 2150,
    likes: 167,
    comments: 52,
    href: "/articles/alive-yuhua",
  },
  {
    id: "8",
    title: "React 19 新特性深度解析",
    excerpt:
      "全面梳理 React 19 正式版带来的变化：Actions、useActionState、use() 等新 API，以及 Server Actions 和 Asset Loading 的改进细节。",
    coverImage: "https://picsum.photos/seed/react19-features/600/400",
    category: "编程",
    publishedAt: new Date("2025-02-18"),
    views: 4390,
    likes: 298,
    comments: 73,
    href: "/articles/react19-new-features",
  },
  {
    id: "9",
    title: "《百年孤独》：孤独是人类共同的语言",
    excerpt:
      "重读马尔克斯，在魔幻现实主义的叙事里，我看到了现代人与孤独相处的永恒命题。关于记忆、时间与家族命运的随想。",
    coverImage: "https://picsum.photos/seed/cien-anos/600/400",
    category: "文学",
    publishedAt: new Date("2024-12-10"),
    views: 1650,
    likes: 128,
    comments: 29,
    href: "/articles/cien-anos-soledad",
  },
  {
    id: "10",
    title: "Tailwind CSS v4 迁移实战记录",
    excerpt:
      "将一个中型项目从 Tailwind v3 迁到 v4 的完整过程。记录踩坑、配置差异和值得注意的 breaking change，省去你自己摸索的时间。",
    coverImage: "https://picsum.photos/seed/tailwind-v4/600/400",
    category: "编程",
    publishedAt: new Date("2024-11-05"),
    views: 3050,
    likes: 221,
    comments: 45,
    href: "/articles/tailwind-v4-migration",
  },
  {
    id: "11",
    title: "Raycast 插件开发入门：用脚本扩展你的工作流",
    excerpt:
      "手把手教你用 Raycast Extension API 开发一个自定义插件，从脚手架到发布，覆盖列表视图、表单、Action 等常用功能模式。",
    coverImage: "https://picsum.photos/seed/raycast-plugin/600/400",
    category: "工具",
    publishedAt: new Date("2024-09-17"),
    views: 1920,
    likes: 156,
    comments: 33,
    href: "/articles/raycast-plugin-dev",
  },
  {
    id: "12",
    title: "《了不起的盖茨比》：美国梦的幻灭与执念",
    excerpt:
      "菲茨杰拉德用盖茨比的一生揭示了欲望与幻象的本质。那道绿光不只是盖茨比的执念，也是每个怀揣梦想的人内心最脆弱的部分。",
    coverImage: "https://picsum.photos/seed/great-gatsby/600/400",
    category: "文学",
    publishedAt: new Date("2024-07-30"),
    views: 1430,
    likes: 112,
    comments: 24,
    href: "/articles/great-gatsby",
  },
];
