export {
  compressImage,
  prepareImageForUpload,
  MAX_IMAGE_BYTES,
  USER_FACING_IMAGE_ERROR_PREFIXES,
  type ImageUploadScene,
} from "./prepare-image-upload";

export {
  ARTICLE_UPLOAD_MAX_BYTES,
  AVATAR_COMPRESS_TRIGGER_BYTES,
  AVATAR_UPLOAD_MAX_BYTES,
  GIF_MAX_BYTES,
  INTERACTIVE_IMAGE_COMPRESS_TARGET_BYTES,
  INTERACTIVE_IMAGE_COMPRESS_TRIGGER_BYTES,
  INTERACTIVE_IMAGE_UPLOAD_MAX_BYTES,
} from "./image-upload-limits";
